Updates startup script

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -1,82 +1,82 @@
 #!/bin/bash
 
-# if ! command -v brew &> /dev/null
-# then
-#     echo "brew could not be found, installing now"
-#     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-# fi
+if ! command -v brew &> /dev/null
+then
+    echo "brew could not be found, installing now"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+fi
 
-# {{ if eq .chezmoi.os "linux" -}}
+{{ if eq .chezmoi.os "linux" -}}
 
-# if ! command -v sudo &> /dev/null
-# then
-#     echo "Installing sudo"
-#     apt update && apt install sudo apt-utils
-# fi
+if ! command -v sudo &> /dev/null
+then
+    echo "Installing sudo"
+    apt update && apt install sudo apt-utils
+fi
 
-# sudo apt update
-# sudo apt install -y curl git gpg kitty
+sudo apt update
+sudo apt install -y curl git gpg kitty
 
-# # 1Password CLI
-# curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
-#  sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
+# 1Password CLI
+curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
+ sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
 
-# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
-#  sudo tee /etc/apt/sources.list.d/1password.list
+echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
+ sudo tee /etc/apt/sources.list.d/1password.list
 
-# sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
-# curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
-# sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
-# sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
-# curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
-# sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
+sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
+curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
+sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
+sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
+curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
+sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
 
-# sudo apt update && sudo apt install -y 1password-cli
+sudo apt update && sudo apt install -y 1password-cli
 
-# {{ else if eq .chezmoi.os "darwin" -}}
+{{ else if eq .chezmoi.os "darwin" -}}
 
-# # Install Homebrew
-# if [ ! command -v brew &> /dev/null ]; then
-#     eval "$(/opt/homebrew/bin/brew shellenv)"
-#     # 1Password CLI
-#     brew install --cask 1password/tap/1password-cli
-#     # Kitty Terminal
-#     brew install --cask kitty
-# fi
+# Install Homebrew
+if [ ! command -v brew &> /dev/null ]; then
+    eval "$(/opt/homebrew/bin/brew shellenv)"
+    # 1Password CLI
+    brew install --cask 1password/tap/1password-cli
+    # Kitty Terminal
+    brew install --cask kitty
+fi
 
-# {{ end -}}
+{{ end -}}
 
 
-# if [ ! command -v op &> /dev/null ]; then
-#     eval "$(op signin)"
-# fi
+if [ ! command -v op &> /dev/null ]; then
+    eval "$(op signin)"
+fi
 
-# # Brew packages
-# for PACKAGE in ack chezmoi git git-delta gitui grep htop neovim openssh starship tmux tree zsh kubectl
+# Brew packages
+for PACKAGE in ack chezmoi git git-delta gitui grep htop neovim openssh starship tmux tree zsh kubectl
 
-# do
-# 	brew list $PACKAGE || brew install $PACKAGE
-# done
+do
+	brew list $PACKAGE || brew install $PACKAGE
+done
 
-# # Install fzf
-# if [ ! -d "$HOME/.fzf" ]; then
-#     echo "fzf could not be found, installing now"
-#     git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
-#     $HOME/.fzf/install --bin
-# fi
+# Install fzf
+if [ ! -d "$HOME/.fzf" ]; then
+    echo "fzf could not be found, installing now"
+    git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
+    $HOME/.fzf/install --bin
+fi
 
-# # Install oh my zsh
-# if [ ! -d "$HOME/.oh-my-zsh" ]; then
-#     echo "Oh-My-Zsh is not installed, installing now" 
-#     git clone https://github.com/ohmyzsh/ohmyzsh.git $HOME/.oh-my-zsh
-#     chsh -s $(which zsh)
-# fi
+# Install oh my zsh
+if [ ! -d "$HOME/.oh-my-zsh" ]; then
+    echo "Oh-My-Zsh is not installed, installing now" 
+    git clone https://github.com/ohmyzsh/ohmyzsh.git $HOME/.oh-my-zsh
+    chsh -s $(which zsh)
+fi
 
-# # Install Packer NeoVim Package Management
-# if [ ! -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
-#     git clone --depth 1 https://github.com/wbthomason/packer.nvim\
-#         $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
-# fi
+# Install Packer NeoVim Package Management
+if [ ! -d "$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim" ]; then
+    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
+        $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
+fi
 
 # Setup 1Password SSH Agent
 if [[ ! -d "$HOME/.1password" ]]; then
@@ -85,7 +85,7 @@ if [[ ! -d "$HOME/.1password" ]]; then
 fi
 
 if  [[ ! -f "$HOME/.1password/agent.sock" ]]; then
-    if [ "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]; then
+    if [[ -f "$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" ]]; then
         echo "Linking $HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock to $HOME/.1password/agent.sock"
         ln -s $HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock $HOME/.1password/agent.sock
     fi
