Updates for debian

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+if ! command -v brew &> /dev/null
+then
+    echo "brew could not be found, installing now"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+fi
+
 {{ if eq .chezmoi.os "linux" -}}
 
 sudo apt update
@@ -8,19 +14,18 @@ sudo apt install -y ack git htop tmux tree zsh
 {{ else if eq .chezmoi.os "darwin" -}}
 
 # Install Homebrew
-if ! command -v brew &> /dev/null
-then
-    echo "brew could not be found, installing now"
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
+if [ ! command -v brew &> /dev/null ]; then
     eval "$(/opt/homebrew/bin/brew shellenv)"
 fi
 
-for PACKAGE in ack chezmoi git git-delta gitui grep htop mosh neovim openssh starship tmux tree zsh code-minimap
+{{ end -}}
+
+# Brew packages
+for PACKAGE in ack chezmoi git git-delta gitui grep htop mosh neovim openssh starship tmux tree zsh code-minimap kubectl
+
 do
 	brew list $PACKAGE || brew install $PACKAGE
 done
-{{ end -}}
 
 # Install fzf
 if [ ! -d "$HOME/.fzf" ] 
